import ROUTES from '@/routes';

export const sidebarSubmenus = {
  parks: [
    ROUTES.admin.parks.list,
    ROUTES.admin.parks.view.path,
    ROUTES.admin.parks.edit.path,
    ROUTES.admin.parks.create,
  ],
  activities: [
    ROUTES.admin.activities.list,
    ROUTES.admin.activities.create,
    ROUTES.admin.activities.edit.path,
    ROUTES.admin.activities.calendar,
    ROUTES.admin.activities.registrations,
    ROUTES.admin.activities.registrationDetail.path,
    ROUTES.admin.activities.categories.list,
    // ROUTES.admin.activities.categories.create,
    // ROUTES.admin.activities.categories.edit.path,
    ROUTES.admin.activities.instructors.list,
    ROUTES.admin.activities.instructors.create,
    ROUTES.admin.activities.instructors.view.path,
    ROUTES.admin.activities.instructors.edit.path,
  ],
  amenities: [
    ROUTES.admin.amenities.list,
    // ROUTES.admin.amenities.create,
    // ROUTES.admin.amenities.edit.path,
  ],
  trees: [
    ROUTES.admin.trees.list,
    ROUTES.admin.trees.map,
    ROUTES.admin.trees.create,
    // ROUTES.admin.trees.edit.path,
    ROUTES.admin.trees.species.list,
    ROUTES.admin.trees.species.create,
    // ROUTES.admin.trees.species.view.path,
    // ROUTES.admin.trees.species.edit.path,
    ROUTES.admin.trees.maintenance.list,
    // ROUTES.admin.trees.maintenance.create,
    // ROUTES.admin.trees.maintenance.edit.path,
  ],
  fauna: [
    ROUTES.admin.fauna.list,
    // ROUTES.admin.fauna.create,
    // ROUTES.admin.fauna.edit.path,
  ],
  visitors: [
    ROUTES.admin.visitors.count,
    // ROUTES.admin.visitors.create,
    // ROUTES.admin.visitors.edit.path,
    ROUTES.admin.visitors.feedback,
  ],
  events: [
    ROUTES.admin.events.list,
    ROUTES.admin.events.create,
    // ROUTES.admin.events.view.path,
    ROUTES.admin.events.edit.path,
    ROUTES.admin.events.calendar,
    ROUTES.admin.events.registrations,
    ROUTES.admin.events.categories.list,
    // ROUTES.admin.events.categories.create,
    // ROUTES.admin.events.categories.edit.path,
  ],
  spaceReservations: [
    ROUTES.admin.spaceReservations.list,
    ROUTES.admin.spaceReservations.create,
    ROUTES.admin.spaceReservations.edit.path,
    ROUTES.admin.spaceReservations.calendar,
    ROUTES.admin.spaceReservations.spaces.list,
    ROUTES.admin.spaceReservations.spaces.create,
    // ROUTES.admin.spaceReservations.spaces.edit.path,
  ],
  evaluations: [
    ROUTES.admin.evaluations.criteria.list,
    // ROUTES.admin.evaluations.criteria.create,
    // ROUTES.admin.evaluations.criteria.edit,
    ROUTES.admin.evaluations.parks,
    ROUTES.admin.evaluations.activities,
    ROUTES.admin.evaluations.instructors,
    ROUTES.admin.evaluations.events,
    ROUTES.admin.evaluations.volunteers,
    ROUTES.admin.evaluations.concessionaires,
  ],
  assets: [
    ROUTES.admin.assets.list,
    ROUTES.admin.assets.map,
    ROUTES.admin.assets.create,
    ROUTES.admin.assets.view.path,
    ROUTES.admin.assets.edit.path,
    ROUTES.admin.assets.categories.list,
    // ROUTES.admin.assets.categories.create,
    // ROUTES.admin.assets.categories.edit.path,
    // ROUTES.admin.assets.inventory.list,
    // ROUTES.admin.assets.inventory.create,
    // ROUTES.admin.assets.inventory.edit.path,
    ROUTES.admin.assets.assignments.list,
    // ROUTES.admin.assets.assignments.create,
    // ROUTES.admin.assets.assignments.edit.path,
    ROUTES.admin.assets.maintenance.list,
    ROUTES.admin.assets.maintenance.create,
    // ROUTES.admin.assets.maintenance.edit.path,
    ROUTES.admin.assets.maintenance.calendar,
  ],
  incidents: [
    ROUTES.admin.incidents.list,
    ROUTES.admin.incidents.create,
    ROUTES.admin.incidents.view.path,
    // ROUTES.admin.incidents.edit.path,
    ROUTES.admin.incidents.categories.list,
    // ROUTES.admin.incidents.categories.create,
    // ROUTES.admin.incidents.categories.edit.path,
  ],
  warehouse: [
    ROUTES.admin.warehouse.list,
    ROUTES.admin.warehouse.create,
    ROUTES.admin.warehouse.edit.path,
    ROUTES.admin.warehouse.stock.list,
    ROUTES.admin.warehouse.stock.create,
    ROUTES.admin.warehouse.stock.view.path,
    ROUTES.admin.warehouse.stock.edit.path,
    ROUTES.admin.warehouse.movements.list,
    // ROUTES.admin.warehouse.movements.create,
    // ROUTES.admin.warehouse.movements.edit.path,
    ROUTES.admin.warehouse.requisitions.list,
    // ROUTES.admin.warehouse.requisitions.create,
    // ROUTES.admin.warehouse.requisitions.edit.path,
    ROUTES.admin.warehouse.categories.list,
    // ROUTES.admin.warehouse.categories.create,
    // ROUTES.admin.warehouse.categories.edit.path,
  ],
  volunteers: [
    ROUTES.admin.volunteers.list,
    ROUTES.admin.volunteers.create,
    ROUTES.admin.volunteers.edit.path,
    ROUTES.admin.volunteers.participations.list,
    ROUTES.admin.volunteers.participations.create,
    ROUTES.admin.volunteers.participations.view.path,
    ROUTES.admin.volunteers.participations.edit.path,
    ROUTES.admin.volunteers.recognition,
    ROUTES.admin.volunteers.settings,
  ],
  finance: [
    ROUTES.admin.finance.budgetPlanning,
    ROUTES.admin.finance.incomes,
    ROUTES.admin.finance.expenses,
    ROUTES.admin.finance.cashFlowMatrix,
    ROUTES.admin.finance.calculator,
    ROUTES.admin.finance.catalog,
    ROUTES.admin.finance.pendingApproval,
    ROUTES.admin.finance.payments,
  ],
  accounting: [
    ROUTES.admin.accounting.categories,
    ROUTES.admin.accounting.transactions,
    ROUTES.admin.accounting.journalEntries,
    ROUTES.admin.accounting.trialBalance,
    ROUTES.admin.accounting.financialStatements,
    ROUTES.admin.accounting.fixedAssets,
    ROUTES.admin.accounting.integration,
  ],
  concessions: [
    ROUTES.admin.concessions.list,
    ROUTES.admin.concessions.create,
    ROUTES.admin.concessions.edit,
    ROUTES.admin.concessions.concessionaires.list,
    ROUTES.admin.concessions.concessionaires.create,
    ROUTES.admin.concessions.concessionaires.edit,
    ROUTES.admin.concessions.contracts.list,
    ROUTES.admin.concessions.contracts.create,
    ROUTES.admin.concessions.contracts.edit,
    ROUTES.admin.concessions.active.list,
    ROUTES.admin.concessions.active.create,
    ROUTES.admin.concessions.active.edit,
  ],
  marketing: [
    ROUTES.admin.marketing.sponsors.list,
    ROUTES.admin.marketing.sponsors.create,
    ROUTES.admin.marketing.sponsors.edit,
    ROUTES.admin.marketing.contracts.list,
    ROUTES.admin.marketing.contracts.create,
    ROUTES.admin.marketing.contracts.edit,
    ROUTES.admin.marketing.packages.list,
    ROUTES.admin.marketing.packages.create,
    ROUTES.admin.marketing.packages.edit,
    ROUTES.admin.marketing.benefits.list,
    ROUTES.admin.marketing.benefits.create,
    ROUTES.admin.marketing.benefits.edit,
    ROUTES.admin.marketing.events.list,
    ROUTES.admin.marketing.events.create,
    ROUTES.admin.marketing.events.edit,
    ROUTES.admin.marketing.assets.list,
    ROUTES.admin.marketing.assets.create,
  ],
  advertising: [
    ROUTES.admin.advertising.spaces.list,
    ROUTES.admin.advertising.spaces.create,
    ROUTES.admin.advertising.spaces.edit,
    ROUTES.admin.advertising.advertisements.list,
    ROUTES.admin.advertising.advertisements.create,
    ROUTES.admin.advertising.advertisements.edit,
    ROUTES.admin.advertising.campaigns.list,
    ROUTES.admin.advertising.campaigns.create,
    ROUTES.admin.advertising.campaigns.edit,
    ROUTES.admin.advertising.placements.list,
    ROUTES.admin.advertising.placements.create,
    ROUTES.admin.advertising.placements.edit,
  ],
  communications: [
    ROUTES.admin.communications.templates.list,
    ROUTES.admin.communications.templates.create,
    ROUTES.admin.communications.templates.edit,
    ROUTES.admin.communications.queue,
    ROUTES.admin.communications.campaigns.list,
    ROUTES.admin.communications.campaigns.create,
    ROUTES.admin.communications.campaigns.edit,
    ROUTES.admin.communications.bulk,
  ],
  employees: [
    ROUTES.admin.hr.employees.list,
    ROUTES.admin.hr.employees.create,
    ROUTES.admin.hr.employees.edit,
  ],
  timeOff: [
    ROUTES.admin.hr.timeOff.list,
    ROUTES.admin.hr.timeOff.create,
    ROUTES.admin.hr.timeOff.edit,
  ],
  training: [
    ROUTES.admin.hr.training.list,
    ROUTES.admin.hr.training.create,
    ROUTES.admin.hr.training.edit,
  ],
  payroll: [
    ROUTES.admin.hr.payroll.list,
    ROUTES.admin.hr.payroll.create,
    ROUTES.admin.hr.payroll.edit,
    ROUTES.admin.hr.receipts.list,
    ROUTES.admin.hr.receipts.create,
    ROUTES.admin.hr.receipts.edit,
  ],
  timeTracking: [
    ROUTES.admin.hr.timeTracking,
  ],
  wellness: [
    ROUTES.admin.hr.wellness,
  ],
  access: [
    ROUTES.admin.settings.roles.list,
    ROUTES.admin.settings.roles.create,
    ROUTES.admin.settings.roles.edit,
    ROUTES.admin.settings.permissions,
    ROUTES.admin.settings.users.list,
    ROUTES.admin.settings.users.create,
    ROUTES.admin.settings.users.edit,
  ],
  policies: [
    ROUTES.admin.settings.policies,
  ],
  notifications: [
    ROUTES.admin.settings.notifications,
  ],
  audit: [
    ROUTES.admin.settings.audit,
  ],
  maintenance: [
    ROUTES.admin.settings.backup,
  ],
};

export const sidebarMeta = {
  parks: {
    label: 'navigation.parks',
    icon: 'Trees',
    permissionSlugs: ['parks.view'], // Actualiza según tu sistema
  },
  activities: {
    label: 'navigation.activities',
    icon: 'Boxes',
    permissionSlugs: ['activities.view'],
  },
  amenities: {
    label: 'navigation.amenities',
    icon: 'Package',
    permissionSlugs: ['amenities.view'],
  },
  trees: {
    label: 'navigation.trees',
    icon: 'TreePine',
    permissionSlugs: ['trees.view'],
  },
  fauna: {
    label: 'navigation.fauna',
    icon: 'Binoculars',
    permissionSlugs: ['fauna.view'],
  },
  visitors: {
    label: 'navigation.visitors',
    icon: 'Users',
    permissionSlugs: ['visitors.view'],
  },
  events: {
    label: 'navigation.events',
    icon: 'CalendarDays',
    permissionSlugs: ['events.view'],
  },
  spaceReservations: {
    label: 'navigation.reservations',
    icon: 'CalendarClock',
    permissionSlugs: ['reservations.view'],
  },
  evaluations: {
    label: 'navigation.evaluations',
    icon: 'Star',
    permissionSlugs: ['evaluations.view'],
  },
  assets: {
    label: 'navigation.assets',
    icon: 'Package',
    permissionSlugs: ['assets.view'],
  },
  incidents: {
    label: 'navigation.incidents',
    icon: 'AlertTriangle',
    permissionSlugs: ['incidents.view'],
  },
  warehouse: {
    label: 'navigation.warehouse',
    icon: 'Archive',
    permissionSlugs: ['warehouse.view'],
  },
  volunteers: {
    label: 'navigation.volunteers',
    icon: 'HeartHandshake',
    permissionSlugs: ['volunteers.view'],
  },
  finance: {
    label: 'navigation.finance',
    icon: 'DollarSign',
    permissionSlugs: ['finance.view'],
  },
  accounting: {
    label: 'navigation.accounting',
    icon: 'Calculator',
    permissionSlugs: ['accounting.view'],
  },
  concessions: {
    label: 'navigation.concessions',
    icon: 'Store',
    permissionSlugs: ['concessions.view'],
  },
  marketing: {
    label: 'navigation.marketing',
    icon: 'Megaphone',
    permissionSlugs: ['marketing.view'],
  },
  advertising: {
    label: 'navigation.advertising',
    icon: 'BarChart3',
    permissionSlugs: ['advertising.view'],
  },
  communications: {
    label: 'navigation.communications',
    icon: 'Mail',
    permissionSlugs: ['communications.view'],
  },
  employees: {
    label: 'navigation.employees',
    icon: 'UserCog',
    permissionSlugs: ['employees.view'],
  },
  timeOff: {
    label: 'navigation.timeOff',
    icon: 'Calendar',
    permissionSlugs: ['timeOff.view'],
  },
  training: {
    label: 'navigation.training',
    icon: 'GraduationCap',
    permissionSlugs: ['training.view'],
  },
  payroll: {
    label: 'navigation.payroll',
    icon: 'DollarSign',
    permissionSlugs: ['payroll.view'],
  },
  timeTracking: {
    label: 'navigation.timeTracking',
    icon: 'Clock',
    permissionSlugs: ['timeTracking.view'],
  },
  wellness: {
    label: 'navigation.wellness',
    icon: 'Heart',
    permissionSlugs: ['wellness.view'],
  },
  access: {
    label: 'navigation.access',
    icon: 'Shield',
    permissionSlugs: ['settings.access.view'],
  },
  policies: {
    label: 'navigation.policies',
    icon: 'ClipboardList',
    permissionSlugs: ['settings.policies.view'],
  },
  notifications: {
    label: 'navigation.notifications',
    icon: 'Bell',
    permissionSlugs: ['settings.notifications.view'],
  },
  audit: {
    label: 'navigation.audit',
    icon: 'ClipboardCheck',
    permissionSlugs: ['settings.audit.view'],
  },
  maintenance: {
    label: 'navigation.maintenance',
    icon: 'Download', // No se usa explícitamente en AdminSidebarComplete.tsx, puedes ajustar si tienes otro ícono en mente
    permissionSlugs: ['settings.maintenance.view'],
  },
};