import ROUTES from '@/routes';
import {
  Trees,
  Boxes,
  Package,
  TreePine,
  Binoculars,
  Users,
  CalendarDays,
  CalendarClock,
  Star,
  AlertTriangle,
  Archive,
  HeartHandshake,
  DollarSign,
  Calculator,
  Store,
  Megaphone,
  BarChart3,
  Mail,
  UserCog,
  Calendar,
  GraduationCap,
  Clock,
  Heart,
  Shield,
  ClipboardList,
  Bell,
  ClipboardCheck,
  Download,
  // Iconos adicionales para rutas navegables
  List,
  MapPin,
  UserCheck,
  Tag,
  Shovel,
  MessageSquare,
  Wrench,
  PackagePlus,
  ArrowRightLeft,
  Award,
  Target,
  TrendingUp,
  BookOpen,
  CreditCard,
  FileText,
  Scale,
  Building,
  Grid,
  Handshake,
  Gift,
  LayoutGrid,
  ListChecks,
  Settings,
  Receipt,
  type LucideIcon,
  NotebookPen,
  Leaf,
  UserSearch,
} from 'lucide-react';

// Tipo para la metadata de los submenús
interface SubmenuMeta {
  label: string;
  icon: LucideIcon;
  permissionSlugs: string[];
}

// Estructura de rutas por submenu
export const sidebarSubmenus = {
  parks: [
    ROUTES.admin.parks.list,
    ROUTES.admin.parks.view.path,
    ROUTES.admin.parks.edit.path,
    ROUTES.admin.parks.create,
  ],
  activities: [
    ROUTES.admin.activities.list,
    ROUTES.admin.activities.create,
    ROUTES.admin.activities.edit.path,
    ROUTES.admin.activities.calendar,
    ROUTES.admin.activities.registrations,
    ROUTES.admin.activities.registrationDetail.path,
    ROUTES.admin.activities.categories.list,
    ROUTES.admin.activities.instructors.list,
    ROUTES.admin.activities.instructors.create,
    ROUTES.admin.activities.instructors.view.path,
    ROUTES.admin.activities.instructors.edit.path,
  ],
  amenities: [
    ROUTES.admin.amenities.list,
  ],
  trees: [
    ROUTES.admin.trees.list,
    ROUTES.admin.trees.map,
    ROUTES.admin.trees.create,
    ROUTES.admin.trees.species.list,
    ROUTES.admin.trees.species.create,
    ROUTES.admin.trees.maintenance.list,
  ],
  fauna: [
    ROUTES.admin.fauna.list,
  ],
  visitors: [
    ROUTES.admin.visitors.count,
    ROUTES.admin.visitors.feedback,
  ],
  events: [
    ROUTES.admin.events.list,
    ROUTES.admin.events.create,
    ROUTES.admin.events.edit.path,
    ROUTES.admin.events.calendar,
    ROUTES.admin.events.registrations,
    ROUTES.admin.events.categories.list,
  ],
  spaceReservations: [
    ROUTES.admin.spaceReservations.list,
    ROUTES.admin.spaceReservations.create,
    ROUTES.admin.spaceReservations.edit.path,
    ROUTES.admin.spaceReservations.calendar,
    ROUTES.admin.spaceReservations.spaces.list,
    ROUTES.admin.spaceReservations.spaces.create,
  ],
  evaluations: [
    ROUTES.admin.evaluations.criteria.list,
    ROUTES.admin.evaluations.parks,
    ROUTES.admin.evaluations.activities,
    ROUTES.admin.evaluations.instructors,
    ROUTES.admin.evaluations.events,
    ROUTES.admin.evaluations.volunteers,
    ROUTES.admin.evaluations.concessionaires,
  ],
  assets: [
    ROUTES.admin.assets.list,
    ROUTES.admin.assets.map,
    ROUTES.admin.assets.create,
    ROUTES.admin.assets.view.path,
    ROUTES.admin.assets.edit.path,
    ROUTES.admin.assets.categories.list,
    ROUTES.admin.assets.assignments.list,
    ROUTES.admin.assets.maintenance.list,
    ROUTES.admin.assets.maintenance.create,
    ROUTES.admin.assets.maintenance.calendar,
  ],
  incidents: [
    ROUTES.admin.incidents.list,
    ROUTES.admin.incidents.create,
    ROUTES.admin.incidents.view.path,
    ROUTES.admin.incidents.categories.list,
  ],
  workOrders: [
    ROUTES.admin.workOrders.list,
    ROUTES.admin.workOrders.create,
    ROUTES.admin.workOrders.view.path,
  ],
  warehouse: [
    ROUTES.admin.warehouse.list,
    ROUTES.admin.warehouse.create,
    ROUTES.admin.warehouse.edit.path,
    ROUTES.admin.warehouse.stock.list,
    ROUTES.admin.warehouse.stock.create,
    ROUTES.admin.warehouse.stock.view.path,
    ROUTES.admin.warehouse.stock.edit.path,
    ROUTES.admin.warehouse.movements.list,
    ROUTES.admin.warehouse.requisitions.list,
    ROUTES.admin.warehouse.categories.list,
  ],
  volunteers: [
    ROUTES.admin.volunteers.list,
    ROUTES.admin.volunteers.create,
    ROUTES.admin.volunteers.edit.path,
    ROUTES.admin.volunteers.activities.list,
    ROUTES.admin.volunteers.activities.create,
    ROUTES.admin.volunteers.activities.view.path,
    ROUTES.admin.volunteers.activities.edit.path,
    ROUTES.admin.volunteers.participations.list,
    ROUTES.admin.volunteers.participations.create,
    ROUTES.admin.volunteers.participations.edit.path,
    ROUTES.admin.volunteers.recognition,
  ],
  finance: [
    ROUTES.admin.finance.budgetPlanning,
    ROUTES.admin.finance.incomes,
    ROUTES.admin.finance.expenses,
    ROUTES.admin.finance.cashFlowMatrix,
    ROUTES.admin.finance.calculator,
    ROUTES.admin.finance.catalog,
    ROUTES.admin.finance.pendingApproval,
    ROUTES.admin.finance.payments,
  ],
  accounting: [
    ROUTES.admin.accounting.categories,
    ROUTES.admin.accounting.transactions,
    ROUTES.admin.accounting.journalEntries,
    ROUTES.admin.accounting.trialBalance,
    ROUTES.admin.accounting.financialStatements,
    ROUTES.admin.accounting.fixedAssets,
    ROUTES.admin.accounting.integration,
  ],
  concessions: [
    ROUTES.admin.concessions.list,
    ROUTES.admin.concessions.create,
    ROUTES.admin.concessions.edit.path,
    ROUTES.admin.concessions.concessionaires.list,
    ROUTES.admin.concessions.concessionaires.create,
    ROUTES.admin.concessions.concessionaires.edit.path,
    ROUTES.admin.concessions.contracts.list,
    ROUTES.admin.concessions.contracts.create,
    ROUTES.admin.concessions.contracts.edit.path,
    ROUTES.admin.concessions.active.list,
    ROUTES.admin.concessions.active.create,
    ROUTES.admin.concessions.active.edit.path,
  ],
  marketing: [
    ROUTES.admin.marketing.sponsors.list,
    ROUTES.admin.marketing.sponsors.create,
    ROUTES.admin.marketing.sponsors.edit.path,
    ROUTES.admin.marketing.contracts.list,
    ROUTES.admin.marketing.contracts.create,
    ROUTES.admin.marketing.contracts.edit.path,
    ROUTES.admin.marketing.packages.list,
    ROUTES.admin.marketing.packages.create,
    ROUTES.admin.marketing.packages.edit.path,
    ROUTES.admin.marketing.benefits.list,
    ROUTES.admin.marketing.benefits.create,
    ROUTES.admin.marketing.benefits.edit.path,
    ROUTES.admin.marketing.events.list,
    ROUTES.admin.marketing.events.create,
    ROUTES.admin.marketing.events.edit.path,
    ROUTES.admin.marketing.assets.list,
    ROUTES.admin.marketing.assets.create,
  ],
  advertising: [
    ROUTES.admin.advertising.spaces.list,
    ROUTES.admin.advertising.spaces.create,
    ROUTES.admin.advertising.spaces.edit.path,
    ROUTES.admin.advertising.advertisements.list,
    ROUTES.admin.advertising.advertisements.create,
    ROUTES.admin.advertising.advertisements.edit.path,
    ROUTES.admin.advertising.campaigns.list,
    ROUTES.admin.advertising.campaigns.create,
    ROUTES.admin.advertising.campaigns.edit.path,
    ROUTES.admin.advertising.placements.list,
    ROUTES.admin.advertising.placements.create,
    ROUTES.admin.advertising.placements.edit.path,
  ],
  communications: [
    ROUTES.admin.communications.templates.list,
    ROUTES.admin.communications.templates.create,
    ROUTES.admin.communications.templates.edit.path,
    ROUTES.admin.communications.queue,
    ROUTES.admin.communications.campaigns.list,
    ROUTES.admin.communications.campaigns.create,
    ROUTES.admin.communications.campaigns.edit.path,
    ROUTES.admin.communications.bulk,
  ],
  employees: [
    ROUTES.admin.hr.employees.list,
    ROUTES.admin.hr.employees.create,
    ROUTES.admin.hr.employees.edit.path,
  ],
  timeOff: [
    ROUTES.admin.hr.timeOff.list,
    ROUTES.admin.hr.timeOff.create,
    ROUTES.admin.hr.timeOff.edit.path,
  ],
  training: [
    ROUTES.admin.hr.training.list,
    ROUTES.admin.hr.training.create,
    ROUTES.admin.hr.training.edit.path,
  ],
  payroll: [
    ROUTES.admin.hr.payroll.list,
    ROUTES.admin.hr.payroll.create,
    ROUTES.admin.hr.payroll.edit.path,
    ROUTES.admin.hr.receipts.list,
    ROUTES.admin.hr.receipts.create,
    ROUTES.admin.hr.receipts.edit.path,
  ],
  timeTracking: [
    ROUTES.admin.hr.timeTracking,
  ],
  wellness: [
    ROUTES.admin.hr.wellness,
  ],
  access: [
    ROUTES.admin.settings.roles.list,
    ROUTES.admin.settings.roles.create,
    ROUTES.admin.settings.roles.edit.path,
    ROUTES.admin.settings.permissions,
    ROUTES.admin.settings.users.list,
    ROUTES.admin.settings.users.create,
    ROUTES.admin.settings.users.edit.path,
  ],
  policies: [
    ROUTES.admin.settings.policies,
  ],
  notifications: [
    ROUTES.admin.settings.notifications,
  ],
  audit: [
    ROUTES.admin.settings.audit,
  ],
  maintenance: [
    ROUTES.admin.settings.backup,
  ],
};

// Metadata de submenús (íconos y labels principales)
export const sidebarMeta: Record<string, SubmenuMeta> = {
  parks: {
    label: 'navigation.parks',
    icon: Trees,
    permissionSlugs: ['parks.view'],
  },
  activities: {
    label: 'navigation.activities',
    icon: Boxes,
    permissionSlugs: ['activities.view'],
  },
  amenities: {
    label: 'navigation.amenities',
    icon: Package,
    permissionSlugs: ['amenities.view'],
  },
  trees: {
    label: 'navigation.trees',
    icon: TreePine,
    permissionSlugs: ['trees.view'],
  },
  fauna: {
    label: 'navigation.fauna',
    icon: Binoculars,
    permissionSlugs: ['fauna.view'],
  },
  visitors: {
    label: 'navigation.visitors',
    icon: Users,
    permissionSlugs: ['visitors.view'],
  },
  events: {
    label: 'navigation.events',
    icon: CalendarDays,
    permissionSlugs: ['events.view'],
  },
  spaceReservations: {
    label: 'navigation.reservations',
    icon: CalendarClock,
    permissionSlugs: ['reservations.view'],
  },
  evaluations: {
    label: 'navigation.evaluations',
    icon: Star,
    permissionSlugs: ['evaluations.view'],
  },
  assets: {
    label: 'navigation.assets',
    icon: Package,
    permissionSlugs: ['assets.view'],
  },
  incidents: {
    label: 'navigation.incidents',
    icon: AlertTriangle,
    permissionSlugs: ['incidents.view'],
  },
  workOrders: {
    label: 'navigation.workOrders',
    icon: FileText,
    permissionSlugs: ['workOrders.view'],
  },
  warehouse: {
    label: 'navigation.warehouse',
    icon: Archive,
    permissionSlugs: ['warehouse.view'],
  },
  volunteers: {
    label: 'navigation.volunteers',
    icon: HeartHandshake,
    permissionSlugs: ['volunteers.view'],
  },
  finance: {
    label: 'navigation.finance',
    icon: DollarSign,
    permissionSlugs: ['finance.view'],
  },
  accounting: {
    label: 'navigation.accounting',
    icon: Calculator,
    permissionSlugs: ['accounting.view'],
  },
  concessions: {
    label: 'navigation.concessions',
    icon: Store,
    permissionSlugs: ['concessions.view'],
  },
  marketing: {
    label: 'navigation.marketing',
    icon: Megaphone,
    permissionSlugs: ['marketing.view'],
  },
  advertising: {
    label: 'navigation.advertising',
    icon: BarChart3,
    permissionSlugs: ['advertising.view'],
  },
  communications: {
    label: 'navigation.communications',
    icon: Mail,
    permissionSlugs: ['communications.view'],
  },
  employees: {
    label: 'navigation.employees',
    icon: UserCog,
    permissionSlugs: ['employees.view'],
  },
  timeOff: {
    label: 'navigation.timeOff',
    icon: Calendar,
    permissionSlugs: ['timeOff.view'],
  },
  training: {
    label: 'navigation.training',
    icon: GraduationCap,
    permissionSlugs: ['training.view'],
  },
  payroll: {
    label: 'navigation.payroll',
    icon: DollarSign,
    permissionSlugs: ['payroll.view'],
  },
  timeTracking: {
    label: 'navigation.timeTracking',
    icon: Clock,
    permissionSlugs: ['timeTracking.view'],
  },
  wellness: {
    label: 'navigation.wellness',
    icon: Heart,
    permissionSlugs: ['wellness.view'],
  },
  access: {
    label: 'navigation.access',
    icon: Shield,
    permissionSlugs: ['settings.access.view'],
  },
  policies: {
    label: 'navigation.policies',
    icon: ClipboardList,
    permissionSlugs: ['settings.policies.view'],
  },
  notifications: {
    label: 'navigation.notifications',
    icon: Bell,
    permissionSlugs: ['settings.notifications.view'],
  },
  audit: {
    label: 'navigation.audit',
    icon: ClipboardCheck,
    permissionSlugs: ['settings.audit.view'],
  },
  maintenance: {
    label: 'navigation.maintenance',
    icon: Download,
    permissionSlugs: ['settings.maintenance.view'],
  },
};

// Metadata completa para rutas navegables (solo páginas principales, sin create/edit/view)
export const navigableRoutes: Record<string, Array<{
  route: string;
  labelKey: string;
  icon: LucideIcon;
}>> = {
  activities: [
    { route: ROUTES.admin.activities.list, labelKey: 'navigation.catalog', icon: List },
    { route: ROUTES.admin.activities.calendar, labelKey: 'navigation.calendar', icon: Calendar },
    { route: ROUTES.admin.activities.categories.list, labelKey: 'navigation.categories', icon: Tag },
    { route: ROUTES.admin.activities.registrations, labelKey: 'navigation.registrations', icon: UserCheck },
    { route: ROUTES.admin.activities.instructors.list, labelKey: 'navigation.instructors', icon: GraduationCap },
  ],
  trees: [
    { route: ROUTES.admin.trees.list, labelKey: 'navigation.inventory', icon: NotebookPen },
    { route: ROUTES.admin.trees.map, labelKey: 'navigation.operation', icon: MapPin },
    { route: ROUTES.admin.trees.species.list, labelKey: 'navigation.species', icon: Leaf },
    { route: ROUTES.admin.trees.maintenance.list, labelKey: 'navigation.maintenance', icon: Shovel },
  ],
  visitors: [
    { route: ROUTES.admin.visitors.count, labelKey: 'navigation.count', icon: UserSearch },
    { route: ROUTES.admin.visitors.feedback, labelKey: 'navigation.feedback', icon: MessageSquare },
  ],
  events: [
    { route: ROUTES.admin.events.list, labelKey: 'navigation.catalog', icon: List },
    { route: ROUTES.admin.events.calendar, labelKey: 'navigation.calendar', icon: Calendar },
    { route: ROUTES.admin.events.registrations, labelKey: 'navigation.registrations', icon: UserCheck },
    { route: ROUTES.admin.events.categories.list, labelKey: 'navigation.categories', icon: Tag },
  ],
  spaceReservations: [
    { route: ROUTES.admin.spaceReservations.list, labelKey: 'navigation.management', icon: List },
    { route: ROUTES.admin.spaceReservations.calendar, labelKey: 'navigation.calendar', icon: Calendar },
    { route: ROUTES.admin.spaceReservations.spaces.list, labelKey: 'navigation.spaces', icon: MapPin },
  ],
  evaluations: [
    { route: ROUTES.admin.evaluations.criteria.list, labelKey: 'navigation.criteria', icon: Settings },
    { route: ROUTES.admin.evaluations.parks, labelKey: 'navigation.parks', icon: Trees },
    { route: ROUTES.admin.evaluations.activities, labelKey: 'navigation.activities', icon: Boxes },
    { route: ROUTES.admin.evaluations.instructors, labelKey: 'navigation.instructors', icon: GraduationCap },
    { route: ROUTES.admin.evaluations.events, labelKey: 'navigation.events', icon: CalendarDays },
    { route: ROUTES.admin.evaluations.volunteers, labelKey: 'navigation.volunteers', icon: HeartHandshake },
    { route: ROUTES.admin.evaluations.concessionaires, labelKey: 'navigation.concessionaires', icon: Store },
  ],
  assets: [
    { route: ROUTES.admin.assets.list, labelKey: 'navigation.inventory', icon: List },
    { route: ROUTES.admin.assets.map, labelKey: 'navigation.map', icon: MapPin },
    { route: ROUTES.admin.assets.categories.list, labelKey: 'navigation.categories', icon: Tag },
    { route: ROUTES.admin.assets.assignments.list, labelKey: 'navigation.assignments', icon: UserCheck },
    { route: ROUTES.admin.assets.maintenance.list, labelKey: 'navigation.maintenance', icon: Wrench },
    { route: ROUTES.admin.assets.maintenance.calendar, labelKey: 'navigation.calendar', icon: Calendar },
  ],
  incidents: [
    { route: ROUTES.admin.incidents.list, labelKey: 'navigation.management', icon: List },
    { route: ROUTES.admin.incidents.categories.list, labelKey: 'navigation.categories', icon: Tag },
  ],
  warehouse: [
    { route: ROUTES.admin.warehouse.list, labelKey: 'navigation.catalog', icon: Archive },
    { route: ROUTES.admin.warehouse.stock.list, labelKey: 'navigation.stock', icon: PackagePlus },
    { route: ROUTES.admin.warehouse.movements.list, labelKey: 'navigation.movements', icon: ArrowRightLeft },
    { route: ROUTES.admin.warehouse.requisitions.list, labelKey: 'navigation.requisitions', icon: ClipboardCheck },
    { route: ROUTES.admin.warehouse.categories.list, labelKey: 'navigation.categories', icon: Tag },
  ],
  volunteers: [
    { route: ROUTES.admin.volunteers.list, labelKey: 'navigation.management', icon: List },
    { route: ROUTES.admin.volunteers.activities.list, labelKey: 'navigation.activities', icon: Calendar },
    { route: ROUTES.admin.volunteers.participations.list, labelKey: 'navigation.participations', icon: UserCheck },
    { route: ROUTES.admin.volunteers.recognition, labelKey: 'navigation.recognitions', icon: Award },
  ],
  finance: [
    { route: ROUTES.admin.finance.budgetPlanning, labelKey: 'navigation.budgets', icon: Target },
    { route: ROUTES.admin.finance.incomes, labelKey: 'navigation.incomes', icon: TrendingUp },
    { route: ROUTES.admin.finance.expenses, labelKey: 'navigation.expenses', icon: DollarSign },
    { route: ROUTES.admin.finance.cashFlowMatrix, labelKey: 'navigation.cashFlow', icon: ArrowRightLeft },
    { route: ROUTES.admin.finance.calculator, labelKey: 'navigation.calculator', icon: Calculator },
    { route: ROUTES.admin.finance.catalog, labelKey: 'navigation.catalog', icon: BookOpen },
    { route: ROUTES.admin.finance.pendingApproval, labelKey: 'navigation.pendingApproval', icon: ClipboardCheck },
    { route: ROUTES.admin.finance.payments, labelKey: 'navigation.payments', icon: CreditCard },
  ],
  accounting: [
    { route: ROUTES.admin.accounting.categories, labelKey: 'navigation.categories', icon: Tag },
    { route: ROUTES.admin.accounting.transactions, labelKey: 'navigation.transactions', icon: ArrowRightLeft },
    { route: ROUTES.admin.accounting.journalEntries, labelKey: 'navigation.journalEntries', icon: FileText },
    { route: ROUTES.admin.accounting.trialBalance, labelKey: 'navigation.trialBalance', icon: Scale },
    { route: ROUTES.admin.accounting.financialStatements, labelKey: 'navigation.financialStatements', icon: BarChart3 },
    { route: ROUTES.admin.accounting.fixedAssets, labelKey: 'navigation.fixedAssets', icon: Building },
    { route: ROUTES.admin.accounting.integration, labelKey: 'navigation.integration', icon: Grid },
  ],
  concessions: [
    { route: ROUTES.admin.concessions.list, labelKey: 'navigation.management', icon: List },
    { route: ROUTES.admin.concessions.concessionaires.list, labelKey: 'navigation.concessionaires', icon: Users },
    { route: ROUTES.admin.concessions.contracts.list, labelKey: 'navigation.contracts', icon: FileText },
    { route: ROUTES.admin.concessions.active.list, labelKey: 'navigation.active', icon: Store },
  ],
  marketing: [
    { route: ROUTES.admin.marketing.sponsors.list, labelKey: 'navigation.sponsors', icon: Handshake },
    { route: ROUTES.admin.marketing.contracts.list, labelKey: 'navigation.contracts', icon: FileText },
    { route: ROUTES.admin.marketing.packages.list, labelKey: 'navigation.packages', icon: Package },
    { route: ROUTES.admin.marketing.benefits.list, labelKey: 'navigation.benefits', icon: Gift },
    { route: ROUTES.admin.marketing.events.list, labelKey: 'navigation.events', icon: CalendarDays },
    { route: ROUTES.admin.marketing.assets.list, labelKey: 'navigation.assets', icon: LayoutGrid },
  ],
  advertising: [
    { route: ROUTES.admin.advertising.spaces.list, labelKey: 'navigation.spaces', icon: LayoutGrid },
    { route: ROUTES.admin.advertising.advertisements.list, labelKey: 'navigation.advertisements', icon: Target },
    { route: ROUTES.admin.advertising.campaigns.list, labelKey: 'navigation.campaigns', icon: Megaphone },
    { route: ROUTES.admin.advertising.placements.list, labelKey: 'navigation.placements', icon: MapPin },
  ],
  communications: [
    { route: ROUTES.admin.communications.templates.list, labelKey: 'navigation.templates', icon: FileText },
    { route: ROUTES.admin.communications.queue, labelKey: 'navigation.queue', icon: ListChecks },
    { route: ROUTES.admin.communications.campaigns.list, labelKey: 'navigation.campaigns', icon: Megaphone },
    { route: ROUTES.admin.communications.bulk, labelKey: 'navigation.bulk', icon: Mail },
  ],
  payroll: [
    { route: ROUTES.admin.hr.payroll.list, labelKey: 'navigation.management', icon: DollarSign },
    { route: ROUTES.admin.hr.receipts.list, labelKey: 'navigation.receipts', icon: Receipt },
  ],
  access: [
    { route: ROUTES.admin.settings.roles.list, labelKey: 'navigation.roles', icon: UserCog },
    { route: ROUTES.admin.settings.permissions, labelKey: 'navigation.permissions', icon: Grid },
    { route: ROUTES.admin.settings.users.list, labelKey: 'navigation.users', icon: Users },
  ],
};